### ISSUE TITLE
FLORES+ dev in Chuvash

### ISSUE THREAD

**Issue by AlAntonov** [openlanguagedata/flores#1]
Hello, please consider our contribution. FLORES+ dev in Chuvash

[chv_Cyrl.md](https://github.com/openlanguagedata/flores/files/14075388/chv_Cyrl.md)
[chv.dev.txt](https://github.com/openlanguagedata/flores/files/14075403/chv.dev.txt)

**Comment by jeanm** [comment]
Thanks @AlAntonov! The data has now been added to v2.0-rc.1 and can be downloaded in the Releases page. We expect to release the final v2.0 in the coming month.
