### ISSUE TITLE
Add FLORES+ dev set in the Meadow Mari language.

### ISSUE THREAD

**Issue by avidale** [openlanguagedata/flores#2]
On behalf of Andrey Chemyshev @fu-lab, I am requesting to add the dev subset of FLORES+ in the Meadow (Eastern) Mari language.
A pull request with the language card will be added shortly. 

Here are the translations: [mhr_Cyrl.dev.txt](https://github.com/openlanguagedata/flores/files/14261728/mhr_Cyrl.dev.txt)

**Comment by avidale** [comment]
@laurieburchell @jeanm thanks for integrating the language cards!
Is anything else required for adding the data itself to the next relaese of FLORES+?

**Comment by jeanm** [comment]
Thanks @fu-lab and @avidale! The data has now been added to v2.0-rc.1 and can be downloaded in the Releases page. We expect to release the final v2.0 in the coming month.
